version: '3'

services:

  homeoffice-db:
    image: debezium/postgres:latest
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U homeofficeuser -d homeofficedb"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - POSTGRES_USER=homeofficeuser
      - POSTGRES_PASSWORD=redhat-21
      - POSTGRES_DB=homeofficedb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - my-network

  zookeeper:
    image: debezium/zookeeper:1.3
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - my-network

  kafka:
    image: debezium/kafka:1.3
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my-network

networks:
  my-network:
    name: homeoffice-network
